package com.kingmarco.myclientmodel.Auxiliary.Enums;

public enum SnackBarsInfo {
    DATA_ERROR,
    CARTS_ERROR,
    EXIST_ERROR,
    DELETE_ERROR,
    IMAGES_ERROR,
    LOGIN_ERROR,
    REGISTER_ERROR,
    DISABLE_ERROR,
    CHATS_ERROR,
    EMAIL_SERVER_ERROR,
    EMAILS_EQUALS_ERROR,
    EMAIL_INCORRECT_ERROR,
    PASSWORD_EQUALS_ERROR,
    PASSWORD_LENGTH_ERROR,
    INCOMPLETE_INFO_ERROR,
    EMAIL_SUCCESS,
    PASSWORD_SUCCESS,
    LOGIN_SUCCESS,
    LOG_OUT_SUCCESS,
    UPLOAD_SUCCESS,
    UPDATE_SUCCESS,
    DELETE_SUCCESS
}
